---
output: html_fragment
bibliography: biblio.bib
---

#### Development

GCM compareR has been developed by Javier Fajardo, Derek Corcoran, Patrick Roehrdanz, Lee Hannah and Pablo Marquet in <a href = "http://marquet.cl/" target = "_blank">Marquet Lab</a> in Pontificia Universidad Católica de Chile, in Santiago de Chile. It was built as part of the <a href = "http://www.sparc-website.org/" target = "_blank">Spatial Planning for Protected Areas in Response to Climate Change initiative (SPARC)</a> project, a GEF initiative leaded by Conservation International (CI), and with the support of <a href = "http://ieb-chile.cl/" target = "_blank">Instituto de Ecología y Biodiversidad (IEB)</a> in Chile.

***

#### Authors  
<a href = "https://scholar.google.es/citations?user=L30b63UAAAAJ&hl=es&oi=ao" target = "_blank">Javier Fajardo  
<a href = "https://derek-corcoran-barrios.github.io/" target = "_blank">Derek Corcoran</a>  
Patrick Roehrdanz  
Lee Hannah  
<a href = "http://marquet.cl/" target = "_blank">Pablo Marquet</a>  

***

#### Climatic data

This application uses downscaled climate data published by Worldclim and  CGIAR-CCAFS under CC 4.0 license. CMIP6 data was obtained from <a href = "https://www.worldclim.org/" target = "_blank">Worldclim</a> and is based on Worldclim2.0 bioclimatic variables. CMIP5 data was obtained from CGIAR-CCAFS (Research Program on Climate Change, Agriculture and Food Security) and is based on Worldclim1.4 bioclimatic variables.

All the raster data used by GCM compareR is available from the above mentioned data portals (<a href = "https://www.worldclim.org/data/cmip6/cmip6climate.html" target = "_blank">Worldclim</a> and <a href = "http://ccafs-climate.org/" target = "_blank">CCAFS</a>). CCAFS data is also available through their R package [@Chamberlain2017].

Please, don't forget to <a href = "https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html" target = "_blank">check usage and citation requirements of climate modeling groups and cite appropriately</a>.

***

#### References
